development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:90f705bebf3fd92607e4b6241de3662b@jack.redistogo.com:11852/
  channel_prefix: langeschool_production


# production: &production
#   adapter: redis
#   url: redis://10.10.3.153:6381
# development: &development
#   adapter: redis
#   url: redis://localhost:6379
# test: *development
