development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:90f705bebf3fd92607e4b6241de3662b@jack.redistogo.com:11852/
  # channel_prefix: langeschool_production
